### ISSUE TITLE
It feels like there is something wrong with the code（openlane/pinmux/config.tcl.tcl）

### ISSUE THREAD

**Issue by pengpeng-lian** [dineshannayya/riscduino#12]
########/openlane/pinmux/config.tcl#################

set ::env(FP_IO_VEXTEND) {6}
set ::env(FP_IO_HEXTEND) {6}

set ::env(FP_IO_VEXTEND) 4
set ::env(FP_IO_HEXTEND) 4

Would these two paragraphs be duplicated?

**Comment by dineshannayya** [comment]
Yes, this is duplicated. Typically tool picks the last config.  I have clean-up the script and updated into repo.  Thanks for the Review.
