### ISSUE TITLE
access latency about the sky130_sram?

### ISSUE THREAD

**Issue by clp510** [dineshannayya/riscduino#18]
From the waveform I see there are 2 access latency when reading the sky130_sram, can I have 1 clock latency sky130 sram?

**Comment by dineshannayya** [comment]
Typically Memory will register the address for one cycle and data will be available in next cycle only. Currently only Limited version of SRAM released for tape-out.  You can check with OpenRam team if they have any plan for this.
[https://github.com/VLSIDA/OpenRAM]

**Comment by clp510** [comment]
OK，thanks a lot
