### ISSUE TITLE
Problems with ‘make user_project_wrapper'

### ISSUE THREAD

**Issue by pengpeng-lian** [dineshannayya/riscduino#19]
####################error#######################################
OpenLane UNKNOWN
(with mounted scripts from couldn't create error file for command: **permission denied**)
All rights reserved. (c) 2020-2022 Efabless Corporation and contributors.
Available under the Apache License, version 2.0. See the LICENSE file for more details.

couldn't create error file for command: **permission denied**

**Comment by dineshannayya** [comment]
No clarity on how you are running this repo and where ..
