### ISSUE TITLE
Die status

### ISSUE THREAD

**Issue by Sya0** [dineshannayya/riscduino#2]
I saw, in e-fabless website, that your project tape-out has been done properly. I am wondering that did your chip run flawlessly in real world?

**Comment by dineshannayya** [comment]
efabless tape-out happened as planned date. But still we have not received silicon back for MPW-2 shuttle itself .. 
I have successfully able to place Riscduino in  MPW-3 shuttle and Revised version in MPW-4 and MPW-5.    
I am also eagerly waiting for Silicon & results.

**Comment by Sya0** [comment]
thanks for the reply.
